create_data_manager:
  particle: pion
  extra_sample_config:
    particle: pion2
    path: '/home/amaevskiy/temporary/MC_calibsample/'
create_gan:
  name: SimpleModelPionExtraSample
create_summary_makers:
- period_in_epochs: 10
- period_in_epochs: 10
  split: extra
create_training_manager:
  epochs: 500
  save_interval_in_epochs: 10
