create_data_manager:
  data_path: "/home/amaevskiy/data/RICHGAN/pid_gan_data_extractor/"
  particle: pion
  extra_sample_config:
    particle: MC_pion_from_Dst
    path: '/home/amaevskiy/data/RICHGAN/csv_outputs/'
    csv_delimiter: ","
    feature_columns:
    - P
    - ETA
    - NumSPDHits
    target_columns:
    - RichDLLe
    - RichDLLk
    - RichDLLmu
    - RichDLLp
    - RichDLLbt
    weight_column: probe_sWeight
  test_size: 0.1
  feature_columns:
  - Brunel_P
  - Brunel_ETA
  - nSPDhits
  preprocessor_config:
    classname: WeightBypassPreprocessor
    weight_col_name: probe_sWeight
    preprocessor_config:
        classname: QuantileTransformer
        output_distribution: normal
        n_quantiles: 50000
        subsample: 10000000000
create_gan:
  name: SimpleModelPionMC
create_summary_makers:
- period_in_epochs: 100
  split: extra
create_training_manager:
  epochs: 5000
  save_interval_in_epochs: 100
  batch_size: 17000
