create_data_manager:
  data_path: /home/sergey/lhcb_stack/my_data/mix_dataset/
  extra_sample_config:
    csv_delimiter: ','
    feature_columns:
    - P
    - ETA
    - NumSPDHits
    particle: MC_muon_from_Bu_JpsiK
    path: /home/sergey/lhcb_stack/my_data/stripping_data_extractor/csv_outputs/
    target_columns:
    - RichDLLe
    - RichDLLk
    - RichDLLmu
    - RichDLLp
    - RichDLLbt
    weight_column: probe_sWeight
  feature_columns:
  - Brunel_P
  - Brunel_ETA
  - nSPDhits
  particle: muon
  preprocessor_config:
    classname: WeightBypassPreprocessor
    preprocessor_config:
      classname: QuantileTransformer
      n_quantiles: 50000
      output_distribution: normal
      subsample: 10000000000
    weight_col_name: probe_sWeight
  test_size: 0.1
create_gan:
  name: SimpleModelPionMC
create_summary_makers:
- period_in_epochs: 100
  split: val
create_training_manager:
  batch_size: 17000
  epochs: 5000
  save_interval_in_epochs: 100
